version: '2.3'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
  app:
    build: .
    volumes:
      ## copy project files to /var/www ##
      - .:/var/www
    working_dir: /var/www
  db:
    image: mysql:5.7
    ports:
      - "3388:3306"
    volumes:
      - ./docker-volumes-data/db:/var/lib/database
    environment:
      MYSQL_DATABASE: servicedesk_2.0
      MYSQL_ROOT_PASSWORD: p44sswordaptika2019
  redis:
    image: redis
    volumes:
      - ./docker-volumes-data/redis:/data